[package]
name = "tatami-auth"
description = "SSH user authentication state machines for Tatami"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[features]
default = []

[dependencies]
tatami-wire = { workspace = true, features = ["alloc"] }
tatami-keys = { workspace = true }
